# Generated by Django 5.2 on 2025-04-21 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
