# Generated by Django 5.2 on 2025-05-02 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='TaskType',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='type',
            new_name='tasktype',
        ),
    ]
