# Generated by Django 5.2 on 2025-05-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_type_tasktype_rename_type_task_tasktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_projected_time_external',
            field=models.TimeField(default='00:00.000'),
        ),
        migrations.AddField(
            model_name='project',
            name='total_projected_time_internal',
            field=models.TimeField(default='00:00.000'),
        ),
    ]
