# Generated by Django 5.2 on 2025-05-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_duration_projected_external_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, null=True, related_name='unlocks', to='tasks.task'),
        ),
    ]
