# Generated by Django 5.2 on 2025-05-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='cycle_group',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
