# Generated by Django 5.2 on 2025-05-05 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_cycle_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='source_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='start',
            field=models.DateField(),
        ),
    ]
