# Generated by Django 5.2 on 2025-05-05 20:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_cycle_daypart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='daypart',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('morning', 'ochtend'), ('afternoon', 'namiddag'), ('evening', 'avond'), ('full', 'volledige dag')], max_length=50), blank=True, default=list, size=None),
        ),
    ]
