# Generated by Django 5.2 on 2025-05-05 20:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_cycle_daypart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='every_day',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='cycle',
            name='every_month',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='cycle',
            name='every_week',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='cycle',
            name='every_year',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='level',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('days', 'dagen'), ('weeks', 'weken'), ('months', 'maanden'), ('years', 'jaren')], max_length=50), blank=True, default=list, size=None),
        ),
    ]
