# Generated by Django 5.2 on 2025-05-05 21:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_cycle_every_day_cycle_every_month_cycle_every_week_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cycle',
            old_name='cycle_distance',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='daypart',
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='every_day',
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='every_month',
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='every_week',
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='every_year',
        ),
        migrations.AddField(
            model_name='cycle',
            name='cycle_model',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('each', 'elke'), ('every', 'om de'), ('dayofweek', 'dag(en) van de week'), ('monthsofyear', 'maand(en) van het jaar'), ('firstlastof', 'eerste/laatste van'), ('dayofmonth', 'dag van de maand')], max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='cycle',
            name='one_level',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('day', 'dag'), ('week', 'week'), ('month', 'maand'), ('year', 'jaar')], max_length=50), blank=True, default=list, size=None),
        ),
    ]
