# Generated by Django 5.2 on 2025-05-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_rename_cycle_distance_cycle_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='days_of_level',
        ),
        migrations.AlterField(
            model_name='cycle',
            name='level',
            field=models.CharField(blank=True, choices=[('days', 'dagen'), ('weeks', 'weken'), ('months', 'maanden'), ('years', 'jaren')], default=list, max_length=50),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='one_level',
            field=models.CharField(blank=True, choices=[('day', 'dag'), ('week', 'week'), ('month', 'maand'), ('year', 'jaar')], default=list, max_length=50),
        ),
    ]
