# Generated by Django 5.2 on 2025-05-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_remove_cycle_days_of_level_alter_cycle_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='level',
            field=models.CharField(blank=True, choices=[('days', 'dagen'), ('weeks', 'weken'), ('months', 'maanden'), ('years', 'jaren')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='one_level',
            field=models.CharField(blank=True, choices=[('day', 'dag'), ('week', 'week'), ('month', 'maand'), ('year', 'jaar')], max_length=50),
        ),
    ]
