# Generated by Django 5.2 on 2025-05-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_cycle_level_alter_cycle_one_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='cycle_model',
            field=models.CharField(blank=True, choices=[('each', 'elke'), ('every', 'om de'), ('dayofweek', 'dag(en) van de week'), ('monthsofyear', 'maand(en) van het jaar'), ('firstlastof', 'eerste/laatste van'), ('dayofmonth', 'dag van de maand')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='level',
            field=models.CharField(blank=True, choices=[('days', 'dagen'), ('weeks', 'weken'), ('months', 'maanden'), ('years', 'jaren')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='month',
            field=models.CharField(blank=True, choices=[('January', 'januari'), ('February', 'februari'), ('March', 'maart'), ('April', 'april'), ('May', 'mei'), ('June', 'juni'), ('July', 'juli'), ('August', 'augustus'), ('September', 'september'), ('October', 'oktober'), ('November', 'november'), ('December', 'december')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='one_level',
            field=models.CharField(blank=True, choices=[('day', 'dag'), ('week', 'week'), ('month', 'maand'), ('year', 'jaar')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='weekday',
            field=models.CharField(blank=True, choices=[('Monday', 'maandag'), ('Tuesday', 'dinsdag'), ('Wednesday', 'woensdag'), ('Thursday', 'donderdag'), ('Friday', 'vrijdag'), ('Saturday', 'zaterdag'), ('Sunday', 'zondag')], default='', max_length=50),
        ),
    ]
