# Generated by Django 5.2 on 2025-05-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_cycle_cycle_model_alter_cycle_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, null=True, related_name='unlocks', to='tasks.task'),
        ),
    ]
