# Generated by Django 5.2 on 2025-05-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_task_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='unlocks', to='tasks.task'),
        ),
    ]
