# Generated by Django 5.2 on 2025-06-22 16:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_alter_cycle_source_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='date',
        ),
        migrations.AddField(
            model_name='meeting',
            name='enddate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='meeting',
            name='startdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
