# Generated by Django 5.2 on 2025-06-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_remove_meeting_date_meeting_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='enddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='startdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
