# Generated by Django 5.2 on 2025-06-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_date_of_birth'),
        ('tasks', '0020_alter_meeting_enddate_alter_meeting_startdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-startdate']},
        ),
        migrations.AlterField(
            model_name='meeting',
            name='contacts',
            field=models.ManyToManyField(blank=True, through='tasks.MeetingContextContact', to='contacts.contextcontact'),
        ),
    ]
