# Generated by Django 5.2 on 2025-06-22 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_alter_meeting_options_alter_meeting_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingcontextcontact',
            name='status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.meetingacceptance'),
        ),
    ]
