# Generated by Django 5.2 on 2025-06-22 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_alter_meetingcontextcontact_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingcontextcontact',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.meetingacceptance'),
        ),
    ]
